version: "3"
services:
  mlflow:
    build:
      context: mlflow/
    command:
      - bash
      - -c
      - "mlflow server --backend-store-uri sqlite:////mlflow/mlflow.db --serve-artifacts --host 0.0.0.0 --port 5040"
    ports:
      - "5040:5040"
    volumes:
      - ./run_env/data:/mlflow
